// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4HRLwEDj-UdoDOpN6ZkpQOVQ5dSxdvjs',
    appId: '1:109088270982:web:7996d63f489e216c4f7f07',
    messagingSenderId: '109088270982',
    projectId: 'smart-parking-mrcc',
    authDomain: 'smart-parking-mrcc.firebaseapp.com',
    storageBucket: 'smart-parking-mrcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtNGrKyWEHLFwt06rLx5L9bbapueNcoDw',
    appId: '1:109088270982:android:62d626378fb556804f7f07',
    messagingSenderId: '109088270982',
    projectId: 'smart-parking-mrcc',
    storageBucket: 'smart-parking-mrcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOiUFymnnWAE4YbcVrJsKRIFE6_vwklN0',
    appId: '1:109088270982:ios:2abd4b257afc0e404f7f07',
    messagingSenderId: '109088270982',
    projectId: 'smart-parking-mrcc',
    storageBucket: 'smart-parking-mrcc.firebasestorage.app',
    iosBundleId: 'com.example.pryFinalParqueadero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOiUFymnnWAE4YbcVrJsKRIFE6_vwklN0',
    appId: '1:109088270982:ios:2abd4b257afc0e404f7f07',
    messagingSenderId: '109088270982',
    projectId: 'smart-parking-mrcc',
    storageBucket: 'smart-parking-mrcc.firebasestorage.app',
    iosBundleId: 'com.example.pryFinalParqueadero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4HRLwEDj-UdoDOpN6ZkpQOVQ5dSxdvjs',
    appId: '1:109088270982:web:f519586bb821a3454f7f07',
    messagingSenderId: '109088270982',
    projectId: 'smart-parking-mrcc',
    authDomain: 'smart-parking-mrcc.firebaseapp.com',
    storageBucket: 'smart-parking-mrcc.firebasestorage.app',
  );
}
